# Pandas

### Reading data 
1. df=pd.read_csv("sales_data_sample.csv",encoding="latin1")<br>
2. df=pd.read_excel("SampleSuperstore.xlsx")<br>
3. df=pd.read_json("sample_Data.json")
4. if the data is in cloud then should use gcsfs

In [2]:
import pandas as pd

df=pd.read_csv("sales_data_sample.csv",encoding='latin1')
print(df)

      ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00
1           10121               34      81.35                5  2765.90
2           10134               41      94.74                2  3884.34
3           10145               45      83.26                6  3746.70
4           10159               49     100.00               14  5205.27
...           ...              ...        ...              ...      ...
2818        10350               20     100.00               15  2244.40
2819        10373               29     100.00                1  3978.51
2820        10386               43     100.00                4  5417.57
2821        10397               34      62.24                1  2116.16
2822        10414               47      65.52                9  3079.44

            ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0      2/24/2003 0:00   Shipped       1         2     2003  ...
1       5/7/2003 0:00   Shipped       2         5     2003  ...
2       7/1/2003 0:00   Shipped       3         7     2003  ...
3      8/25/2003 0:00   Shipped       3         8     2003  ...
4     10/10/2003 0:00   Shipped       4        10     2003  ...
...               ...       ...     ...       ...      ...  ...
2818   12/2/2004 0:00   Shipped       4        12     2004  ...
2819   1/31/2005 0:00   Shipped       1         1     2005  ...
2820    3/1/2005 0:00  Resolved       1         3     2005  ...
2821   3/28/2005 0:00   Shipped       1         3     2005  ...
2822    5/6/2005 0:00   On Hold       2         5     2005  ...

                       ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0           897 Long Airport Avenue           NaN            NYC    NY
1                59 rue de l'Abbaye           NaN          Reims   NaN
2     27 rue du Colonel Pierre Avia           NaN          Paris   NaN
3                78934 Hillside Dr.           NaN       Pasadena    CA
4                   7734 Strong St.           NaN  San Francisco    CA
...                             ...           ...            ...   ...
2818             C/ Moralzarzal, 86           NaN         Madrid   NaN
2819                    Torikatu 38           NaN           Oulu   NaN
2820             C/ Moralzarzal, 86           NaN         Madrid   NaN
2821          1 rue Alsace-Lorraine           NaN       Toulouse   NaN
2822             8616 Spinnaker Dr.           NaN         Boston    MA

     POSTALCODE  COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0         10022      USA       NaN              Yu             Kwai    Small
1         51100   France      EMEA         Henriot             Paul    Small
2         75508   France      EMEA        Da Cunha           Daniel   Medium
3         90003      USA       NaN           Young            Julie   Medium
4           NaN      USA       NaN           Brown            Julie   Medium
...         ...      ...       ...             ...              ...      ...
2818      28034    Spain      EMEA          Freyre            Diego    Small
2819      90110  Finland      EMEA       Koskitalo           Pirkko   Medium
2820      28034    Spain      EMEA          Freyre            Diego   Medium
2821      31000   France      EMEA          Roulet          Annette    Small
2822      51003      USA       NaN         Yoshido             Juri   Medium

[2823 rows x 25 columns]

### Creating and storing

1. df.to_csv("output.csv",index=False)
2. df.to_excel("output.xlsx",index=False)
3. df.to_json("output.json",index=False)

In [ ]:
data={
    "name":["varshan","sathish","karthik"],
    "age":[20,21,22],
    "city":["chennai","bangalore","hyderabad"]
}

df = pd.DataFrame(data)
print(df)

df.to_csv("output.csv",index=False)
"""
if index is true then the index will be written to the file. 
If index is false, then the index will not be written to the file.
"""

      name  age       city
0  varshan   20    chennai
1  sathish   21  bangalore
2  karthik   22  hyderabad

### Exploring the data 

head(): displays top rows (default 5 rows)<br>
tail(): displays least rows (default 5 rows)

In [11]:
data={
    'name':["varshan","sathish","karthik",'sunny','kumar','varshanth','varun','prasad'],
    'age':[20,21,22,20,32,21,30,29],
    'city':["chennai","bangalore","hyderabad",'delhi','mumbai','pune','kolkata','chennai'],
    'salary':[20000,21000,22000,20000,32000,21000,30000,29000]
}
df=pd.DataFrame(data)
print(df.head(2)) # prints first 5 rows of the dataframe
print('---------------------------------------------------------------------------')
print(df.tail(2)) # prints last 5 rows of the dataframe

      name  age       city  salary
0  varshan   20    chennai   20000
1  sathish   21  bangalore   21000
---------------------------------------------------------------------------
     name  age     city  salary
6   varun   30  kolkata   30000
7  prasad   29  chennai   29000

<strong>df.info()</strong> 

-> Gives <strong>structural information</strong> about the DataFrame.<br>
-> Shows <strong>number of rows and columns</strong> .<br>
-> Shows <strong>column names and data types</strong> .<br>
-> Shows <strong>non-null count</strong>  for each column.<br>
-> Shows <strong>memory usage</strong> .<br>

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      object
 1   age     8 non-null      int64
 2   city    8 non-null      object
 3   salary  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes

<strong>df.describe()</strong><br>

-> Gives <strong>statistical summary</strong> of numerical columns.<br>
-> Returns: <strong>count, mean, std, min, 25%, 50%, 75%, max.</strong><br>
-> Helps understand <strong>data distribution and outliers</strong> quickly.<br>

25% (Q1): 25% of the values are less than or equal to this value.<br>
50% (Q2 / Median): 50% of the values are less than or equal to this value.<br>
75% (Q3): 75% of the values are less than or equal to this value.

In [13]:
df.describe() # gives the statistical summary of the dataframe

             age        salary
count   8.000000      8.000000
mean   24.375000  24375.000000
std     5.040904   5040.904114
min    20.000000  20000.000000
25%    20.750000  20750.000000
50%    21.500000  21500.000000
75%    29.250000  29250.000000
max    32.000000  32000.000000

In [19]:
print(df.shape) # gives the number of rows and columns in the dataframe
print()
print(df.columns) # gives the column names of the dataframe
print()
print(df.index) # gives the index of the dataframe
print()
print(df.dtypes) # gives the data types of the columns in the dataframe
print()
print(df.size) # gives the number of elements in the dataframe
print()
print(df.values) # gives the values of the dataframe as a numpy array

(8, 4)

Index(['name', 'age', 'city', 'salary'], dtype='object')

RangeIndex(start=0, stop=8, step=1)

name      object
age        int64
city      object
salary     int64
dtype: object

32

[['varshan' 20 'chennai' 20000]
 ['sathish' 21 'bangalore' 21000]
 ['karthik' 22 'hyderabad' 22000]
 ['sunny' 20 'delhi' 20000]
 ['kumar' 32 'mumbai' 32000]
 ['varshanth' 21 'pune' 21000]
 ['varun' 30 'kolkata' 30000]
 ['prasad' 29 'chennai' 29000]]

<strong>Selecting Specific column</strong>

In [24]:
print(df['name']) # gives the selected column of the dataframe
print('---------------------------------------------------------------------------')
print(df[['name','age']]) # gives the selected columns of the dataframe

0      varshan
1      sathish
2      karthik
3        sunny
4        kumar
5    varshanth
6        varun
7       prasad
Name: name, dtype: object
---------------------------------------------------------------------------
        name  age
0    varshan   20
1    sathish   21
2    karthik   22
3      sunny   20
4      kumar   32
5  varshanth   21
6      varun   30
7     prasad   29

### Filtering rows
boolean indexing

In [28]:
df[df['salary']>25000] # gives the rows where the salary is greater than 20000

     name  age     city  salary
4   kumar   32   mumbai   32000
6   varun   30  kolkata   30000
7  prasad   29  chennai   29000

& -> AND<br>
| -> OR<br>
~ -> NOT

In [33]:
df[(df['salary']>22000) & (df['age']>25)]

     name  age     city  salary
4   kumar   32   mumbai   32000
6   varun   30  kolkata   30000
7  prasad   29  chennai   29000

In [29]:
df[df['age']>25][['name','age']] # gives the rows where the age is greater than 25 and selects the name and age columns

     name  age
4   kumar   32
6   varun   30
7  prasad   29